name: coverage

on: [push]

jobs:
    my_fist_ci_job:
        name: first CI job configuration
        runs-on: ubuntu-latest
        steps:
            - name: Running Bash command to get date and the hostname we are running
              run: date && hostname

    test_coverage:
        name: test coverage
        runs-on: ubuntu-latest
        steps:
            #checkout the head of branch
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v3
              with:
                  python-version: "3.9"
            - name: Install Python dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install coverage
            - name: Generate coverage report
              # display report in std out
              run: |
                  coverage run -m pytest
                  coverage report -m
